#!/usr/bin/perl -w
use strict;
my @input = @ARGV;
if (!@input){
	print STDERR "$0: a script to count plus and minus sRNA read from PatMaN files\n";
	print STDERR "$0 please enter <PatMaN files> generated by using stacked fasta as patterns>\n";
	exit();
}
print "input_file\tplus\tminus\n";
foreach my $file (@input){
	my %seen;
	my $plus;
	my $minus;
	open (FILE, $file) or die "Can't open file $file\n";
	while (<FILE>){
    	if ($_=~m/^(\S+)\s*.*\t(\w+)\((\S+)\)\t(\d+)\t(\d+)\t(\S+)\t\d+/){
			my $name = $1;
			my $start = $4;
			my $end = $5;
			my $sequence = $2;
			my $abundance = $3;
			my $orientation = $6;
			$sequence =~ tr/U/T/;
			$sequence =~ tr/a-z/A-Z/;
			chomp ($orientation, $abundance, $sequence);
			unless ($seen{$sequence}){
			    if ($orientation eq "+"){
					$plus += $abundance;
			    }
			    else {
					$minus += $abundance;
			    }
			    $seen{$sequence}++;
    		}
		}
	}
	if (!$plus){$plus = 0;}
	if (!$minus){$minus = 0;}
	print "$file\t$plus\t$minus\n";
}
# by Levente Kontra
