#!/usr/bin/perl -w
use strict;
my $input = shift;
if (!$input){
	print STDERR "$0: <please enter <patman file> generated by using stacked fasta as pattern>\n";
	print STDERR "No input file given - exiting\n";
	exit();
	}
my %seen;
open (INPUT, "$input") or die "Couldn't open patman input file\n";
while (<INPUT>){
	if ($_=~m/^(\S+)\s*.*\t(\w+)\((\S+)\)\t(\d+)\t(\d+)\t(\S+)\t(\d+)/){
		my $name = $1;
		my $start = $4;
		my $end = $5;
		my $sequence = $2;
		my $abundance = $3;
		my $mm = $7;
		$sequence =~ tr/U/T/;
		$sequence =~ tr/a-z/A-Z/;
		chomp ($name, $start, $end, $abundance, $sequence);
		if ($mm == 0){
			unless ($seen{$sequence}){
				print ">$sequence($abundance)\n$sequence\n";
				$seen{$sequence}++;
			}
		}
	}
}

# by Simon Moxon
